### ISSUE TITLE
Sometimes, journal retrieval fails with a 404 error

### ISSUE THREAD

**Issue by sk-ys** [MayamaTakeshi/redmine_rt#59]
In my environment, sometimes, journal retrieval fails with a 404 error when adding a note with quick notes.
However, when accessed after some time has passed, retrieval works correctly.
I'm concerned that an error may occur because it's called before the journal record is added.

Browser console:
![image](https://github.com/MayamaTakeshi/redmine_rt/assets/963792/5e5da034-10f6-4e41-8c02-880bae721325)

Redmine log:
```
I, [2024-02-25T09:31:52.269199 #7648]  INFO -- : [7c731af8-50ad-454b-9b37-bd958dac4398] Started PUT "/issues/2002/add_quick_notes" for ***.***.***.*** at 2024-02-25 09:31:52 +0900
I, [2024-02-25T09:31:52.270068 #7648]  INFO -- : [7c731af8-50ad-454b-9b37-bd958dac4398] Processing by QuickNotesController#add_quick_notes as TEXT
I, [2024-02-25T09:31:52.270387 #7648]  INFO -- : [7c731af8-50ad-454b-9b37-bd958dac4398]   Parameters: {"issue"=>{"notes"=>"hhh", "private_notes"=>false}, "id"=>"2002"}
I, [2024-02-25T09:31:52.275031 #7648]  INFO -- : [7c731af8-50ad-454b-9b37-bd958dac4398]   Current user: user5 (id=5)
I, [2024-02-25T09:31:52.349999 #7648]  INFO -- : [e76bc4fe-7ad2-452a-b8b1-92254e9db755] Started GET "/journals/12368" for ***.***.***.*** at 2024-02-25 09:31:52 +0900
I, [2024-02-25T09:31:52.350744 #7648]  INFO -- : [e76bc4fe-7ad2-452a-b8b1-92254e9db755] Processing by JournalsController#show as */*
I, [2024-02-25T09:31:52.351029 #7648]  INFO -- : [e76bc4fe-7ad2-452a-b8b1-92254e9db755]   Parameters: {"id"=>"12368"}
I, [2024-02-25T09:31:52.355085 #7648]  INFO -- : [e76bc4fe-7ad2-452a-b8b1-92254e9db755]   Current user: user5 (id=5)
I, [2024-02-25T09:31:52.356533 #7648]  INFO -- : [e76bc4fe-7ad2-452a-b8b1-92254e9db755] Completed 404 Not Found in 5ms (ActiveRecord: 1.3ms | Allocations: 1266)
F, [2024-02-25T09:31:52.357138 #7648] FATAL -- : [e76bc4fe-7ad2-452a-b8b1-92254e9db755]   
[e76bc4fe-7ad2-452a-b8b1-92254e9db755] ActiveRecord::RecordNotFound (Couldn't find Journal with 'id'=12368):
[e76bc4fe-7ad2-452a-b8b1-92254e9db755]   
[e76bc4fe-7ad2-452a-b8b1-92254e9db755] plugins/redmine_rt/lib/redmine_rt/journals_controller_patch.rb:24:in `show'
[e76bc4fe-7ad2-452a-b8b1-92254e9db755] lib/redmine/sudo_mode.rb:61:in `sudo_mode'
I, [2024-02-25T09:31:52.378648 #7648]  INFO -- : [7c731af8-50ad-454b-9b37-bd958dac4398] Completed 200 OK in 108ms (Views: 0.1ms | ActiveRecord: 85.2ms | Allocations: 12486)
I, [2024-02-25T09:31:53.395727 #7648]  INFO -- : [390d8cf4-8b57-4668-b69d-975cad823943] Started GET "/issues/2002" for ***.***.***.*** at 2024-02-25 09:31:53 +0900
I, [2024-02-25T09:31:53.396489 #7648]  INFO -- : [390d8cf4-8b57-4668-b69d-975cad823943] Processing by IssuesController#show as */*
I, [2024-02-25T09:31:53.396768 #7648]  INFO -- : [390d8cf4-8b57-4668-b69d-975cad823943]   Parameters: {"id"=>"2002"}
I, [2024-02-25T09:31:53.401178 #7648]  INFO -- : [390d8cf4-8b57-4668-b69d-975cad823943]   Current user: user5 (id=5)
I, [2024-02-25T09:31:53.462209 #7648]  INFO -- : [390d8cf4-8b57-4668-b69d-975cad823943] STATEMENT projects.id = 11 AND ((issues.status_id IN (SELECT id FROM issue_statuses WHERE is_closed=FALSE)))
I, [2024-02-25T09:31:53.619218 #7648]  INFO -- : [390d8cf4-8b57-4668-b69d-975cad823943]   Rendered inline template (Duration: 0.5ms | Allocations: 290)
I, [2024-02-25T09:31:53.657553 #7648]  INFO -- : [390d8cf4-8b57-4668-b69d-975cad823943]   Rendered layout layouts/base.html.erb (Duration: 192.2ms | Allocations: 109425)
I, [2024-02-25T09:31:53.658106 #7648]  INFO -- : [390d8cf4-8b57-4668-b69d-975cad823943] Completed 200 OK in 261ms (Views: 157.8ms | ActiveRecord: 56.2ms | Allocations: 137965)

```

**Comment by MayamaTakeshi** [comment]
Solution merged. Thanks.
